### ISSUE TITLE
where to add CreateSitemap?

### ISSUE THREAD

**Issue by vc7deo** [zhelyabuzhsky/yii2-sitemap#10]
in which part we add this action CreateSitemap ??

also this part
'sitemap' =>
  [
    'class' => '\zhelyabuzhsky\sitemap\components\Sitemap',
    'maxUrlsCountInFile' => 10000,
    'sitemapDirectory' => 'frontend/web',
  ],

is it inside config/main.php ?

**Comment by pastuhov** [comment]
Yes, inside config/main.php, see http://www.yiiframework.com/doc-2.0/guide-structure-application-components.html

**Comment by zhelyabuzhsky** [comment]
Thank you for your answer, @pastuhov.
In addition, @vc7deo should add action CreateSitemap to console controller.

**Comment by vc7deo** [comment]
ok so.i need to create a controller inside console folder say SitemapController.php and add CreateSitemap into it ??

do i add any other steps???

**Comment by zhelyabuzhsky** [comment]
You are absolutely right, @vc7deo. No other steps.

**Comment by vc7deo** [comment]
hii

i created a SitemapController 

`<?php
namespace console\controllers;

use Yii;
use backend\models\Service;
use yii\console\Controller;
class SitemapController extends Controller {

public function actionCreateSitemap()
{
  Yii::$app->sitemap->addModel(Service::class)->create();
}

}`

but i'm getting following error

![image](https://cloud.githubusercontent.com/assets/8149102/13052124/14ccafae-d423-11e5-8de6-e12f469aaabb.png)

**Comment by zhelyabuzhsky** [comment]
Which version of PHP do you use, @vc7deo?
If your version is lower, than 5.6, try
`Yii::$app->sitemap->addModel(Service::className())->create();`

P.S. fixed usage example

**Comment by vc7deo** [comment]
its 5.4.12

now that error gone.and i got new error..sorry to bother you first time i work with console application.
also i'm calling the model from the backend.

`<?php
namespace console\controllers;

use Yii;
use backend\models\Service;
use yii\console\Controller;
class SitemapController extends Controller {

public function actionCreateSitemap()
{
  Yii::$app->sitemap->addModel(Service::className())->create();
}

}`
![image](https://cloud.githubusercontent.com/assets/8149102/13073089/09155e22-d4c3-11e5-8cda-0d1823f144e4.png)

**Comment by zhelyabuzhsky** [comment]
As you see in stack trace, your model backend\models\Service should implement interface SitemapEntity.

**Comment by vc7deo** [comment]
i got new errors

![image](https://cloud.githubusercontent.com/assets/8149102/13111928/92e6cc76-d5ae-11e5-9ff7-62d84ad3811d.png)

that means i need to add that functions in my model???
if so
can you please tell me the return values of these functions

public function getSitemapLastmod();

public function getSitemapChangefreq();

public function getSitemapPriority();

public function getSitemapLoc();

public static function getSitemapDataSource();

thanks in advance

**Comment by zhelyabuzhsky** [comment]
Example of model which implements SitemapEntity interface you can see [here](https://github.com/zhelyabuzhsky/yii2-sitemap/blob/master/tests/models/Category.php).

**Comment by vc7deo** [comment]
Coooool it worked ..you are the best

i have 3 more queries

![image](https://cloud.githubusercontent.com/assets/8149102/13165687/e517f956-d6e5-11e5-8872-4cbfd04c2e1d.png)

i got this message and this is coming from here i think
  protected function gzipFile()
    {
        $gzipFileName = $this->path . '.gz';
        exec("cat {$this->path} | gzip > $gzipFileName");
    }

and second thing how we add the static links like aboutus,contact us ...etc .Is there any function or setting ???

third is how it'll auto generate sitemap after making site is live(in live server)

**Comment by zhelyabuzhsky** [comment]
Wait please

**Comment by zhelyabuzhsky** [comment]
1. Try again, I rewrote gzip function.
2. You should write special class (Page, for example) that contains all your static urls.
3. Add your new command to cron on your server.

**Comment by vc7deo** [comment]
Thank you for your updation
for the second point.. i have no how to add it.

could you please tell me how to add the urls like 

www.example.com  --- > home
www.example.com/site/about --> about
www.example.com/site/contact --> contact

**Comment by zhelyabuzhsky** [comment]
You should create model that returns this links and also implements SitemapEntity interface.
