### ISSUE TITLE
how use yii2-sitemap?

### ISSUE THREAD

**Issue by Yuriy-Svetlov** [zhelyabuzhsky/yii2-sitemap#14]
Where it need set?
I added in 'components' console.php 
NotWorking!!!
```
'sitemap' =>
  [
    'class' => '\zhelyabuzhsky\sitemap\components\Sitemap',
    'maxUrlsCountInFile' => 10000,
    'sitemapDirectory' => 'frontend/web',
  ],
```

PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'app\commands\Item' not found'

**Comment by zhelyabuzhsky** [comment]
Could you give me your console action code?
(actionCreateSitemap in my example)

**Comment by Yuriy-Svetlov** [comment]
I understood, you extension for yii2-advanced. I use basic version.
```
<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\commands;

use yii\console\Controller;



class HelloController extends Controller
{

    //yii hello/index
    public function actionIndex($message = 'hello world')
    {

      var_dump("expression");
      return $message;
    }
}
```

**Comment by zhelyabuzhsky** [comment]
First of all my extension is for all Yii2 applications, not only for advanced app. Are you sure that this code generates error:

`Fatal Error 'yii\base\ErrorException' with message 'Class 'app\commands\Item' not found'`

**Comment by ak868308** [comment]
Exception 'Error' with message 'Call to a member function batch() on null'

in XXXX/advanced/vendor/zhelyabuzhsky/yii2-sitemap/src/components/Sitemap.php:233

Stack trace:
#0 XXXX/advanced/console/controllers/SitemapController.php(25): zhelyabuzhsky\sitemap\components\Sitemap->create()
#1 [internal function]: console\controllers\SitemapController->actionCreate()
#2 XXXX/advanced/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 XXXX/advanced/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#4 XXXX/advanced/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('create', Array)
#5 XXXX/advanced/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('create', Array)
#6 XXXX/advanced/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('sitemap/create', Array)
#7 XXXX/advanced/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('sitemap/create', Array)
#8 XXXX/advanced/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 XXXX/advanced/yii(27): yii\base\Application->run()
#10 {main}
Please help

**Comment by PaVeL-Ekt** [comment]
Please put the code of your application where you are using Sitemap component.

**Comment by PaVeL-Ekt** [comment]
Presumably, you forgot to specify `use common\model\Item;` directive at the beginning of the file.

**Comment by ak868308** [comment]
Actually I want to create a sitemap using this extension using two databases. I have multiple databases and whenever I am overriding the method getDb() in model it never uses the return database component i.e db2 It always uses the primary connection I am not sure why this is happens. 
Example:
Database A have news table
Databse B have blog table 
and bothe table have slug 

Thanks

**Comment by PaVeL-Ekt** [comment]
I added this feature in #23.

**Comment by ak868308** [comment]
Thank you so much :)
