### ISSUE TITLE
Use hostInfo at sitemap index creation

### ISSUE THREAD

**Issue by nick-denry** [zhelyabuzhsky/yii2-sitemap#24]
Hello!

According to Yii2 docs and url creation practice both params [hostInfo](https://www.yiiframework.com/doc/api/2.0/yii-web-urlmanager#$hostInfo-detail) and [baseUrl](https://www.yiiframework.com/doc/api/2.0/yii-web-urlmanager#$baseUrl-detail) are used.

UrlManager provides two different methods such as [createUrl()](https://www.yiiframework.com/doc/api/2.0/yii-web-urlmanager#createUrl()-detail) and [createAbsoluteUrl()](https://www.yiiframework.com/doc/api/2.0/yii-web-urlmanager#createAbsoluteUrl()-detail). The last one use `hostInfo` param for absolute url creation.

I.e. `baseUrl` could be => '/', '/subdir', 
and `hostInfo` is used as scheme and domain prefix => 'https://example.com'

**Comment by nick-denry** [comment]
I've created PR for this https://github.com/zhelyabuzhsky/yii2-sitemap/pull/25

**Comment by zhelyabuzhsky** [comment]
Thank you very much

**Comment by zhelyabuzhsky** [comment]
PR is approved, so I close this issue =)
