### ISSUE TITLE
Google Bot can't index files from sitemap.xml

### ISSUE THREAD

**Issue by pceuropa** [zhelyabuzhsky/yii2-sitemap#28]
Thank You for plugin but I've probably  problem with setup environments. 
I've created [sitemap file](https://filmydzieci.pl/sitemap.xml) And google boot properly index that file.
But I've received info from google that has problem with index files as /sitemap1.xml.gz, /sitemap2.xml.gz

Then I've removed `.gz` from sitemap.xml and will wait is it help. Actually I haven't more specifics informations but I hope you can suggest some tip.

Currently used version `zhelyabuzhsky/yii2-sitemap         1.2.0`

**Comment by zhelyabuzhsky** [comment]
> But I've received info from google that has problem with index files as /sitemap1.xml.gz, /sitemap2.xml.gz

Can you please show this message from Google?

**Comment by pceuropa** [comment]
I've removed that sitemap from google search console. But if I remember I had `that file couldnt be fetch`

After remove `.gz` from main sitemap.xml I've received that:
![Screenshot at 2020-02-16 12-38-20](https://user-images.githubusercontent.com/9319670/74604045-63662880-50ba-11ea-96a8-d2d09e3b4b79.png)

And in details is

![Screenshot at 2020-02-16 12-38-55](https://user-images.githubusercontent.com/9319670/74604052-682adc80-50ba-11ea-833e-6c92cf6cd74d.png)

I did downgrade to version 1.1.0 and upload sitemaps again. Have to wait for few day on new logs.
I'll you inform.

**Comment by zhelyabuzhsky** [comment]
> I've removed that sitemap from google search console. But if I remember I had that file couldnt be fetch

Are you sure that you actually had the file sitemap34.xml.gz on your web-server?

**Comment by pceuropa** [comment]
Yes, Im sure I had all of xml's. (https://filmydzieci.pl/sitemap.xml)

**Comment by pceuropa** [comment]
Yes I hadn't sitemap34.xml.gz.
But problem is still. Currently i have all files indicated in https://filmydzieci.pl/sitemap.xml
But google say 1, 2, 3 has errors

![Screenshot at 2020-02-23 16-57-53](https://user-images.githubusercontent.com/9319670/75115354-e3156980-565d-11ea-84f8-e1ae4f8686ee.png)

**Comment by zhelyabuzhsky** [comment]
Can you please show me file sitemap1.xml.gz?

**Comment by zhelyabuzhsky** [comment]
Correct file sitemap.xml should be like 

```xml
<sitemap>
  <loc>https://filmydzieci.pl/sitemap1.xml.gz</loc>
  <lastmod>2020-02-23T15:48:09+00:00</lastmod>
</sitemap>
```
(full url with domain name)

Did you fill `hostInfo` and  `baseUrl` parameters in your config like [this](https://github.com/zhelyabuzhsky/yii2-sitemap#1-configure-urlmanager-at-console-config)?

**Comment by pceuropa** [comment]
I haven't set hostInfo and baseURL parameters in my config. 
Thank you @zhelyabuzhsky I feel won't waste your time any more :)

**Comment by zhelyabuzhsky** [comment]
You're welcome =)
